import type { ScrapedPost } from "../types";
import { BROLL_SCRIPT } from "./broll-script";
import { buildComposition } from "./composition";
import { planVideo } from "./plan";
import { fetchSourceVideo, getTimedTranscript, SourceVideoError } from "./transcript";
import type { SceneAsset, VideoLength, VideoPlan } from "./types";

export type BuiltProject = {
  files: Record<string, Uint8Array>;
  plan: VideoPlan;
};

// sana (the free tier's only model) renders people badly — missing heads, extra
// limbs — so prompts steer to places and objects. Belt-and-braces with the
// planner's own guidance.
const NEGATIVE =
  "no text, no letters, no words, no captions, no logos, no watermarks, no visible faces, no deformed anatomy";

function pad(n: number): string {
  return String(n).padStart(2, "0");
}

// Rendering needs Chromium + FFmpeg and the b-roll needs minutes of serial
// fetching — neither fits a serverless function, so both happen locally. This
// README travels with the project so the instructions can't get separated.
function readme(post: ScrapedPost, plan: VideoPlan): string {
  const mins = Math.max(1, Math.round((plan.scenes.length * 45) / 60));
  return [
    `# ${post.author} — b-roll cut`,
    ``,
    `Generated by Glazy's Tools → Post Analysis → "Make a new video".`,
    `The original audio is kept as-is; the visuals are AI b-roll timed to the transcript.`,
    ``,
    `Source: ${post.url}`,
    `Length: ${plan.duration.toFixed(1)}s · ${plan.scenes.length} scenes`,
    ``,
    `## Make it`,
    ``,
    `Needs Node 22+ and FFmpeg (\`brew install ffmpeg\`). Both steps are free.`,
    ``,
    "```bash",
    `node broll.mjs                    # fetch the stills — ~${mins} min, go get a coffee`,
    `npx hyperframes render -o out.mp4 # ~20s`,
    "```",
    ``,
    `\`broll.mjs\` is deliberately slow: the free image service serves one`,
    `request at a time, roughly 45s each. It's resumable — re-run it and it`,
    `skips whatever it already fetched, so a failure costs you only the gaps.`,
    ``,
    `## Change it`,
    ``,
    "```bash",
    `npx hyperframes preview   # scrub the timeline in the browser`,
    `npx hyperframes check     # validate before rendering`,
    "```",
    ``,
    `- Prompts live in \`prompts.json\` — edit one and delete its file in`,
    `  \`assets/\`, then re-run \`node broll.mjs\` to regenerate just that scene.`,
    `- Or drop your own images into \`assets/\` using the same filenames; the`,
    `  fetcher leaves existing files alone.`,
    `- The audio is \`assets/source.mp4\`; the composition reads its track directly.`,
    ``,
  ].join("\n");
}

// Transcribe → plan → assemble a project that fetches its own b-roll and
// renders locally. Fast enough to finish well inside the route's limit,
// because the slow parts are deferred to the user's machine.
export async function buildProject(
  post: ScrapedPost,
  length: VideoLength,
  knownTranscript?: string,
): Promise<BuiltProject> {
  if (!post.videoUrl) {
    throw new SourceVideoError(
      "This post has no video file, so there's no audio to build a new video from.",
    );
  }

  // One download, two uses: Gemini reads it, and it ships as the audio track.
  const source = await fetchSourceVideo(post.videoUrl);
  const transcript = await getTimedTranscript(source, knownTranscript);
  const plan = await planVideo(post, transcript, length);

  const scenes: SceneAsset[] = plan.scenes.map((s, i) => ({
    ...s,
    file: `assets/scene-${pad(i + 1)}.jpg`,
  }));

  // What broll.mjs consumes. Seeded per slot so a re-run reproduces the same
  // visuals rather than a different video.
  const prompts = scenes.map((s, i) => ({
    file: s.file,
    seed: 1000 + i,
    prompt: `${s.imagePrompt}. ${plan.styleNote}. Vertical 9:16 composition. ${NEGATIVE}.`,
  }));

  const enc = new TextEncoder();
  return {
    plan,
    files: {
      "index.html": enc.encode(buildComposition(plan, scenes, { author: post.author })),
      "prompts.json": enc.encode(JSON.stringify(prompts, null, 2)),
      "broll.mjs": enc.encode(BROLL_SCRIPT),
      "README.md": enc.encode(readme(post, plan)),
      "assets/source.mp4": new Uint8Array(source),
    },
  };
}
